Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> from import pico2d *
SyntaxError: invalid syntax
>>> from pico2d import *
Pico2d is prepared.
\
>>> image=load_image('C:\\Users\\박건웅\\Desktop\\사냥꾼의 모험 -2d겜프 프로젝트\\밀림.png')
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    image=load_image('C:\\Users\\박건웅\\Desktop\\사냥꾼의 모험 -2d겜프 프로젝트\\밀림.png')
  File "C:\Users\박건웅\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pico2d.py", line 263, in load_image
    texture = IMG_LoadTexture(renderer, name.encode('UTF-8'))
NameError: name 'renderer' is not defined
>>> open_canvas()
>>> image=load_image('C:\\Users\\박건웅\\Desktop\\사냥꾼의 모험 -2d겜프 프로젝트\\밀림.png')
>>> image.draw(800,600)
>>> update_canvas()
>>> image.draw(0,0)
>>> update_canvas()
>>> image=load_image('C:\\Users\\박건웅\\Desktop\\사냥꾼의 모험 -2d겜프 프로젝트\\밀림.png')
>>> image.draw(800,600)
>>> update_canvas()
>>> image.draw(0,0)
>>> update_canvas()
>>> image.draw(1600,1200)
>>> update_canvas()
>>> clear_canvas()
>>> update_canvas()
>>> image.draw(1600,1200)
>>> update_canvas()
>>> image.draw(800,600)
>>> update_canvas()
>>> image.draw(400,300)
>>> update_canvas()
>>> i=load_image('C:\\Users\\박건웅\\Desktop\\사냥꾼의 모험 -2d겜프 프로젝트\\냥꾼.png')
>>> i.draw_now(100,100)
>>> i=load_image('C:\\Users\\박건웅\\Desktop\\사냥꾼의 모험 -2d겜프 프로젝트\\냥꾼.png')
>>> i.draw_now(100,100)
>>> j=load_image('C:\\Users\\박건웅\\Desktop\\사냥꾼의 모험 -2d겜프 프로젝트\\펭귄2.png')
>>> j.draw_now(0,100)
>>> clear_canvas()
>>> j.draw_now(0,100)
>>> clear_canvas_now()
>>> image=load_image('C:\\Users\\박건웅\\Desktop\\사냥꾼의 모험 -2d겜프 프로젝트\\밀림.png')
>>> image.draw(400,300)
>>> update_canvas()
>>> j.draw_now(50,500)
>>> clear_canvas_now()
>>> image.draw(400,300)
>>> update_canvas()
>>> j.draw_now(50,50)
>>> i.draw_now(150,50)
>>> clear_canvas_now()
>>> image.draw(400,300)
>>> update_canvas()
>>> j.draw_now(50,50)
>>> i.draw_now(130,50)
>>> a=load_image('C:\\Users\\박건웅\\Desktop\\사냥꾼의 모험 -2d겜프 프로젝트\\킁킁이2.png')
>>> b=load_image('C:\\Users\\박건웅\\Desktop\\사냥꾼의 모험 -2d겜프 프로젝트\\길고양이.png')
>>> c=load_image('C:\\Users\\박건웅\\Desktop\\사냥꾼의 모험 -2d겜프 프로젝트\\사바나사자.png')
>>> a.draw_now(300,50)
>>> clear_canvas_now()
>>> image.draw(400,300)
>>> update_canvas()
>>> j.draw_now(50,50)
>>> i.draw_now(150,50)
>>> a.draw_now(300,50)
>>> a.draw_now(400,50)
>>> a.draw_now(300,100)
>>> a=load_image('C:\\Users\\박건웅\\Desktop\\사냥꾼의 모험 -2d겜프 프로젝트\\킁킁이2.png')
>>> b=load_image('C:\\Users\\박건웅\\Desktop\\사냥꾼의 모험 -2d겜프 프로젝트\\길고양이.png')
>>> c=load_image('C:\\Users\\박건웅\\Desktop\\사냥꾼의 모험 -2d겜프 프로젝트\\사바나사자.png')
>>> clear_canvas_now()
>>> image.draw(400,300)
>>> update_canvas()
>>> j.draw_now(50,50)
>>> i.draw_now(150,50)
>>> a.draw_now(300,50)
>>> clear_canvas_now()
>>> image.draw(400,300)
>>> update_canvas()
>>> j.draw_now(50,50)
>>> i.draw_now(150,50)
>>> a.draw_now(400,50)
>>> b.draw_now(500,50)
>>> clear_canvas_now()
>>> image.draw(400,300)
>>> update_canvas()
>>> j.draw_now(50,50)
>>> )
>>>i.draw_now(150,50)
SyntaxError: invalid syntax
>>> )
>>>i.draw_now(150,50)
SyntaxError: invalid syntax
>>> i.draw_now(150,50)
>>> a.draw_now(400,50)
>>> b.draw_now(600,50)
>>> c.draw_now(720,50)
>>> clear_canvas_now()
>>> image.draw(400,300)
>>> update_canvas()
>>> j.draw_now(50,50)
>>> )
>>>i.draw_now(150,50)
SyntaxError: invalid syntax
>>> )
>>>i.draw_now(150,50)
SyntaxError: invalid syntax
>>> i.draw_now(150,50)
>>> a.draw_now(400,50)
>>> b.draw_now(560,50)
>>> c.draw_now(720,50)
>>> 
